import { registerApiKeysHandlers } from "./apikeys";
import { registerComfyUIFreeMemoryHandler } from "./ComfyUI/freeMemoryHandler";
import { registerLaunchComfyDesktopHandler } from "./ComfyUI/launchDesktopHandler";
import { registerComfyUIWorkflowListHandlers } from "./ComfyUI/listWorkflowsHandler";
import { registerReadWorkflowRefHandler } from "./ComfyUI/readWorkflowRefHandler";
import { registerComfyUIRunRecipeHandler } from "./ComfyUI/runRecipeHandler";
import { registerCloseConfirmHandler } from "./close-confirm";
import { registerExportPngHandler } from "./export-png";
import { registerWriteTempFile } from "./filepath";
import { registerImportPngHandler } from "./import-png";
import { registerLMStudioChatHandler } from "./LMStudio/chatHandler";
import { registerLMStudioHandlers } from "./LMStudio/ipcHandlers";
import { registerLMStudioLoadModelHandler } from "./LMStudio/loadModelHandler";
import { registerLoadFileHandler } from "./load-file";
import { registerOpenAIHandlers } from "./openai";
import { registerReadJsonByPathHandler } from "./read-json-by-path";
import { registerSaveHandlers } from "./save";
import { registerSnapshotHandlers } from "./snapshot";
// import { registerOtherServiceHandlers } from "./otherService";

export function registerIpcHandlers(): void {
  registerSnapshotHandlers();
  registerOpenAIHandlers();
  registerSaveHandlers();
  registerCloseConfirmHandler();
  registerLoadFileHandler();
  registerApiKeysHandlers();
  registerLMStudioHandlers();
  registerLMStudioLoadModelHandler();
  registerLMStudioChatHandler();
  registerComfyUIRunRecipeHandler();
  registerComfyUIWorkflowListHandlers();
  registerComfyUIFreeMemoryHandler();
  registerLaunchComfyDesktopHandler();
  registerReadJsonByPathHandler();
  registerReadWorkflowRefHandler();
  registerExportPngHandler();
  registerImportPngHandler();
  registerWriteTempFile();
  // registerOtherServiceHandlers();
}
